Medlink/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Medlink.Data;
using Medlink.Models;
using Microsoft.AspNetCore.Hosting;

namespace Medlink.Controllers
{
    public class PostController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public PostController(ApplicationDbContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }

        // GET: Post
        public async Task<IActionResult> Index()
        {
              return _context.Posts != null ? 
                          View(await _context.Posts.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.Posts'  is null.");
        }

        // PostController.cs
        public async Task<IActionResult> Details(int? id)
        {
            if (UserController.Loginid == null)
            {
                return Redirect("../../User/Login");
            }

            if (id == null || _context.Posts == null)
            {
                return NotFound();
            }

            var postModel = await _context.Posts
                .FirstOrDefaultAsync(m => m.id == id);

            UserModel user = _context.Users.FirstOrDefault(u => u.user_id == postModel.user_id);

            if (postModel == null)
            {
                return NotFound();
            }

            ViewData["Username"] = user.username;

            // Retrieve comments for the post
            var comments = _context.Comments.Where(c => c.post_id == postModel.id).ToList();

            var viewModel = new PostDetailsViewModel
            {
                Post = postModel,
                Comments = comments
            };

            return View(viewModel);
        }


        // GET: Post/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Post/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(PostModel postModel, IFormFile image)
        {
                postModel.user_id = UserController.Loginid;
            if (ModelState.IsValid)
            {
                string imagePath = SaveProfileImage(image);

                // Update the PostModel with the image path
                postModel.image = imagePath;

                _context.Add(postModel);
                await _context.SaveChangesAsync();
                TempData["success"] = "You started a discussion";
                return Redirect($"../Post/Details/{postModel.id}");
            }
            return View(postModel);
        }


        // GET: Post/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Posts == null || UserController.Loginid == null)
            {
                TempData["error"] = "Bad Request";
                return Redirect("../../Home/Index");
            }

            var postModel = await _context.Posts.FindAsync(id);
            if (postModel == null)
            {
                return NotFound();
            }
            return View(postModel);
        }

        // POST: Post/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, PostModel postModel, IFormFile image = null)
        {
            if (id != postModel.id || postModel.user_id != UserController.Loginid)
            {
                TempData["error"] = "Bad request";
                return Redirect("../../User/");
            }

            //if (ModelState.IsValid)
            //{
                try
                {
                  if(image != null && image.Length > 0)
                    {
                        string imagePath = SaveProfileImage(image);

                        // Update the PostModel with the image path
                        postModel.image = imagePath;
                    }
                    else
                    {
                        postModel.image = _context.Posts.AsNoTracking().FirstOrDefault(u => u.id == postModel.id)?.image;
                    }

                    _context.Update(postModel);
                    await _context.SaveChangesAsync();

                    TempData["success"] = "post has been updated";
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PostModelExists(postModel.id))
                    {
                        TempData["error"] = "An error Occured reload";
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                if(UserController.Loginid == "admin")
                {
                    return Redirect("../../Admin/");
                }
                else
                {
                    return Redirect("../../User/");
                }
            //}
            return View(postModel);
        }

        // GET: Post/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Posts == null)
            {
                return NotFound();
            }

            var postModel = await _context.Posts
                .FirstOrDefaultAsync(m => m.id == id);
            UserModel user = _context.Users.FirstOrDefault(u => u.user_id == postModel.user_id);
            if (postModel == null)
            {
                return NotFound();
            }
            ViewData["Username"] = user.username;
            return View(postModel);
        }

        // POST: Post/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Posts == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Posts'  is null.");
            }
            var postModel = await _context.Posts.FindAsync(id);
            if (postModel != null)
            {
                _context.Posts.Remove(postModel);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PostModelExists(int id)
        {
          return (_context.Posts?.Any(e => e.id == id)).GetValueOrDefault();
        }

        private string SaveProfileImage(IFormFile profileImage)
        {
            string uploadsFolder = Path.Combine(_webHostEnvironment.WebRootPath, "uploads");
            string uniqueFileName = Guid.NewGuid().ToString() + "_" + profileImage.FileName;
            string filePath = Path.Combine(uploadsFolder, uniqueFileName);

            using (var stream = new FileStream(filePath, FileMode.Create))
            {
                profileImage.CopyTo(stream);
            }

            return uniqueFileName;
        }
    }
}

Medlink/Controllers/UserController.cs
using Medlink.Data;
using Medlink.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Medlink.Controllers
{
    public class UserController : Controller
    {
        public static string? Loginid { get; set; }
        private readonly ApplicationDbContext _db;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly ILogger<UserController> _logger;

        public UserController(ApplicationDbContext db, IWebHostEnvironment webHostEnvironment, ILogger<UserController> logger)
        {
            _db = db;
            _webHostEnvironment = webHostEnvironment;
            _logger = logger;
        }

        public IActionResult Index()
        {
            if (UserController.Loginid == null)
            {
                return RedirectToAction("Login");
            }
            else if (UserController.Loginid == "Admin123")
            {
                return RedirectToAction("List");
            }
            else
            {
                UserModel user = _db.Users.FirstOrDefault(u => u.user_id == UserController.Loginid);
                IEnumerable<PostModel> posts = _db.Posts.Where(p => p.user_id == UserController.Loginid).ToList();
                return View(Tuple.Create(user, posts));
            }
        }

        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Register(UserModel obj,string repassword, IFormFile profile)
        {
            Guid uniqueId = Guid.NewGuid();

            string uniqueIdString = uniqueId.ToString("N").Substring(0, 10);
            obj.user_id = uniqueIdString;
            if (obj.password != repassword)
            {
                // Add model error for password mismatch
                ModelState.AddModelError("repassword", "Password and confirmation password do not match");
                return View(obj);
            }

            if (profile != null && profile.Length > 0)
            {
                // Save the profile image to a folder or a storage service
                string imagePath = SaveProfileImage(profile);

                // Update the UserModel with the image path
                obj.profile = imagePath;
            }

            if (ModelState.IsValid)
            {
               
                _db.Users.Add(obj);
                _db.SaveChanges();
                TempData["success"] = "Registration Successfull Please login";

                return RedirectToAction("Login");
            }
            return View(obj);
        }


        [HttpGet("Doctor/{id}")]
        public IActionResult Doctor(string id)
        {
            // Retrieve the user with the specified id from the database
            if (id != null)
            {
                UserModel user = _db.Users.FirstOrDefault(u => u.user_id == id);
                IEnumerable<PostModel> posts = _db.Posts.Where(p => p.user_id == id).ToList();
                
                if (id == UserController.Loginid)
                {
                    return RedirectToAction("Index");
                }
                return user != null ? View(Tuple.Create(user, posts)) : RedirectToAction("List");
            }
            return RedirectToAction("List");
        }

        [HttpGet("List/{id?}")]
        public IActionResult List(string? id)
        {
            if (id!= null)
            {
                // Redirect to the Details action when an id is provided
                return RedirectToAction("Doctor", new { id = id });
            }

            // Retrieve and display all users
            IEnumerable<UserModel> userList = _db.Users;
            return View(userList);
        }


        public IActionResult Login()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Login(string email,string password)
        {
            if(password == "Admin123")
            {
                TempData["success"] = "Welcome Admin";
                UserController.Loginid = "Admin123";
                return RedirectToAction("List");
            }
            else
            {
                UserModel user = _db.Users.FirstOrDefault(u => u.email == email);
                if (user != null)
                {
                    if (user.password == password)
                    {
                        UserController.Loginid = user.user_id;
                        TempData["success"] = "login Successful";
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        TempData["warning"] = "login failed the password is incorrect";
                    }
                }
                else
                {
                    TempData["warning"] = "login failed email matched no row in d database";
                }
            }
            return View();
        }


        private string SaveProfileImage(IFormFile profileImage)
        {
            string uploadsFolder = Path.Combine(_webHostEnvironment.WebRootPath, "uploads");
            string uniqueFileName = Guid.NewGuid().ToString() + "_" + profileImage.FileName;
            string filePath = Path.Combine(uploadsFolder, uniqueFileName);

            using (var stream = new FileStream(filePath, FileMode.Create))
            {
                profileImage.CopyTo(stream);
            }

            return uniqueFileName;
        }

        public IActionResult Setting()
        {
            if (UserController.Loginid == null)
            {
                return RedirectToAction("Login");
            }else if (UserController.Loginid == "Admin123")
            {
                return RedirectToAction("List");
            }
            else
            {
                UserModel user = _db.Users.FirstOrDefault(u => u.user_id == UserController.Loginid);
                return View(user);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Setting(UserModel obj,string boolyValue, IFormFile? profile = null)
        {
            try
            {
                if (profile != null && profile.Length > 0)
                {
                    // Save the new profile image to a folder or storage service
                    string newImagePath = SaveProfileImage(profile);

                    // Update the UserModel with the new image path
                    obj.profile = newImagePath;
                }
                else
                {
                    // No new profile image provided, maintain the existing one
                    obj.profile = _db.Users.AsNoTracking().FirstOrDefault(u => u.user_id == obj.user_id)?.profile;
                }
               
                    obj.visibility = boolyValue;

                _db.Users.Update(obj);
                _db.SaveChanges();
                TempData["success"] = "Profile changes saved successfully";

                return View(obj);
            }
            catch (Exception ex)
            {
                LogException(ex);
                TempData["warning"] =  "An error occurred while processing your request.";
            }

            return View(obj);
        }



        private void LogException(Exception ex)
        {
            _logger.LogError($"Exception: {ex.Message}", ex);
        }

        public IActionResult Logout()
        {
            UserController.Loginid = null;
            return Redirect("../Home/");
        }

        public  string GetUserUsername(string userId)
        {
            // Assuming you have a method to retrieve a user by ID
            UserModel? user = _db.Users.FirstOrDefault(u => u.user_id == userId);

            // Check if the user exists
            if (user != null)
            {
                // Return the username
                return user.username;
            }

            // If the user doesn't exist, you can return a default value or handle it accordingly
            return "User Not Found";
        }
    }
}

Medlink/Views/User/Doctor.cshtml
@model Tuple<UserModel, IEnumerable<PostModel>>
@{
    ViewData["Title"] = "Doctor";
    var obj = Model.Item1;
    var posts = Model.Item2;
    int totalPost = posts.ToList().Count;
    var show = "";
    if(obj.profile == "true"){
        show = "Public";
    }else{
        show = "Private";
    }
}
<style>
    .input-group{
        background-color:transparent;
        outline:none;
        border:1px solid rgb(30, 148, 162);
        border-radius:10px;
    }
    .form-control:focus{
         background-color:transparent;
        outline:none;
        border:none;
    }
    .form-control{
         background-color:transparent;
        outline:none;
        border:none;
        border-left:1px solid 1px solid rgb(30, 148, 162);
    }
    .card {
        background-color: rgba(255,255,255,.7);
    }
</style>
<div class="row">
    <div class="card col-lg-3">
        <div class="card-body pb-1">
            <div class="row p-1">
                <div class="col-7">
                    <h5>@show</h5>
                    <img src="@Url.Content("~/uploads/" + obj.profile)" class="rounded-circle img-fluid img-thumbnail" alt="Circular Image">
                </div>
                <div class="m-2">
                    <i> @obj.specialty</i>
                    <h5><i class="fas fa-user fa-sm text-go"></i> @obj.fullname</h5>
                    <h6 class="fw-bolder"><i class="fas fa-user fa-sm text-go"></i> @obj.username</h6>
                    <h6><i class="fas fa-envelope fa-sm text-go"></i> @obj.email</h6>
                    <h6><i class="fas fa-graduation-cap fa-sm text-go"></i> @obj.education</h6>
                    <p>
                        <i class="fas fa-book fa-sm text-go"></i> @obj.bio
                    </p>
                   <form method="post">
                       <div class="input-group" >
                            <input class="form-control" id="message" placeholder="Message body" required/>
                            <button class="input-group-propend btn fas fa-paper-plane text-center p-2 rounded text-go" type="submit"></button>
                       </div>
                   </form>
                </div>
                <h4 class="fw-bolder text-go text-center"> <i class="fas fa-comment"></i> @totalPost  </h4>

            </div>
        </div>
    </div>

    <div class="col-lg-9  pt-2" style="min-height:80vh;max-height:80vh;overflow-y:scroll">
        <h5>Discussions</h5>
         <div class="container mt-4">
            @foreach(var post in posts){

                <div class="card mb-2">
                    <div class="row no-gutters">
                        <!-- Left-aligned image column (col-3) -->
                        <div class="col-md-3">
                            <img src="@Url.Content("~/uploads/" + post.image)" class="card-img" alt="Sample Image">
                        </div>
                        <!-- Details column (col-9) -->
                        <div class="col-md-9">
                            <div class="card-body">
                                <div class="text-go col-12" style="display:flex;justify-content:right;gap:10px">
                                    <a asp-controller="Post" asp-action="Edit" asp-route-id="@post.id"><i class="fas fa-edit text-warning"></i></a>
                                    <a asp-action="Delete" asp-controller="Post" asp-route-id="@post.id"><i class="fas fa-trash-alt text-danger"></i></a>
                                </div>
                                <h5 class="card-title">@post.title</h5>
                                <p class="card-text">@post.details.Substring(0,100)  <a asp-controller="Post" asp-action="Details" asp-route-id="@post.id"> <small>readmore...</small></a> </p>
                                <p class="card-text text-go row">
                                    <small class="text-go col-md-8">@post.created_at</small> 
                                    <span style="text-align:right" class="col-md-4">
                                        <i class="fas fa-thumbs-up"></i> @post.like_count
                                        <i class="fas fa-comment"></i>
                                        <i class="fas fa-comment" style="margin-left:-16px"></i> @post.comment_count
                                    </span>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>

            }
        </div>

    </div>
</div>

Medlink/Views/User/Index.cshtml
@model Tuple<UserModel, IEnumerable<PostModel>>
@{
    ViewData["Title"] = "Index";
    var obj = Model.Item1;
    var posts = Model.Item2;
    int totalPost = posts.ToList().Count;
    var show = "";
    if(obj.visibility == "true"){
        show = "Public";
    }else{
        show = "Private";
    }
}
<style>
    .card{
        background-color:rgba(255,255,255,.7);
    }
</style>
<div class="row">
    <div class="card col-lg-3">
        <div class="card-body pb-1">
            <div class="row p-1">
                <div class="col-7">
                    <h5>@show</h5>
                    <img src="@Url.Content("~/uploads/" + obj.profile)" class="rounded-circle img-fluid img-thumbnail" alt="Circular Image">
                </div>
                <div class="m-2">
                    <i> @obj.specialty</i>
                    <h5><i class="fas fa-user fa-sm text-go"></i> @obj.fullname</h5>
                    <h6 class="fw-bolder"><i class="fas fa-user fa-sm text-go"></i> @obj.username</h6>
                    <h6><i class="fas fa-envelope fa-sm text-go"></i> @obj.email</h6>
                    <h6><i class="fas fa-graduation-cap fa-sm text-go"></i> @obj.education</h6>
                    <p>
                        <i class="fas fa-book fa-sm text-go"></i> @obj.bio</p>
                    <a class="btn text-go col-12 btn-outline-go" asp-controller="Post" asp-action="Create" >
                        Start a discussion <i class="fas fa-comment"></i>
                    </a>
                </div>
                <h4 class="fw-bolder text-go text-center"> <i class="fas fa-comment"></i> @totalPost </h4>
                
            </div>
        </div>
    </div>

    <div class="col-lg-9  pt-2" style="min-height:80vh;max-height:80vh;overflow-y:scroll">
        <h5>My discussions</h5>

        <div class="container mt-4">
            @foreach(var post in posts){
               
                    var truncatedDetails = string.IsNullOrEmpty(post.details) || post.details.Length <= 100
                        ? post.details
                        : post.details.Substring(0, 100);

                <div class="card mb-2">
                    <div class="row no-gutters">
                        <!-- Left-aligned image column (col-3) -->
                        <div class="col-md-3">
                            <img src="@Url.Content("~/uploads/" + post.image)" class="card-img" alt="Sample Image">
                        </div>
                        <!-- Details column (col-9) -->
                        <div class="col-md-9">
                            <div class="card-body">
                                <div class="text-go col-12" style="display:flex;justify-content:right;gap:10px">
                                    <a asp-controller="Post" asp-action="Edit" asp-route-id="@post.id"><i class="fas fa-edit text-warning"></i></a>
                                    <a asp-action="Delete" asp-controller="Post" asp-route-id="@post.id"><i class="fas fa-trash-alt text-danger"></i></a>
                                </div>
                                <h5 class="card-title">@post.title</h5>
                                <p class="card-text">@truncatedDetails <a asp-controller="Post" asp-action="Details" asp-route-id="@post.id"> <small>readmore...</small></a> </p>
                                <p class="card-text text-go row">
                                    <small class="text-go col-md-8">@post.created_at</small> 
                                    <span style="text-align:right" class="col-md-4">
                                        <i class="fas fa-thumbs-up"></i> @post.like_count
                                        <i class="fas fa-comment"></i>
                                        <i class="fas fa-comment" style="margin-left:-16px"></i> @post.comment_count
                                    </span>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>

            }
        </div>

    </div>
</div>

Medlink/Views/User/List.cshtml
@model IEnumerable<UserModel>;
@{
    ViewData["Title"] = "List";
}
<style>
    .input-group{
        background-color:transparent;
        outline:none;
        border:1px solid rgb(30, 148, 162);
        border-radius:10px;
    }
    .form-control:focus{
         background-color:transparent;
        outline:none;
        border:none;
    }
    .form-control{
         background-color:transparent;
        outline:none;
        border:none;
        border-left:1px solid 1px solid rgb(30, 148, 162);
    }
    .card{
        background-color:rgba(255,255,255,.7);
    }
    
</style>
<div class="row">
    <h5 class="col-lg-6">Doctors</h5>
    <div class="col-lg-6">
        <div class="input-group" >
            <span class="input-group-propend fas fa-search text-center p-2 rounded"></span>
            <input class="form-control" id="searchid" placeholder="Type to search"/>
        </div>
    </div>
</div>

<div class="container mt-4">
    <div class="row">
       @foreach(var obj in Model){
            @if(obj.visibility == "true"){
                <div class="col-md-3 mb-4 card-container">
                    <!-- Content for the first column -->
                    <div class="card">
                        <div class="card-body">
                            <div class="row p-1">
                                <div class="col-lg-12 col-3 text-lg-center">
                                    <img src="@Url.Content("~/uploads/" + obj.profile)" class="rounded-circle img-fluid img-thumbnail" alt="Circular Image">
                                </div>
                                <div class="col-lg-12 col-7 m-2">
                                    <h5>@obj.fullname</h5>
                                    <i class="fw-bolder">@obj.username</i>
                                    <h6>@obj.specialty</h6>
                                </div>
                                <a class="btn text-go col-12" style="display:flex;justify-content:right" asp-controller="User" asp-action="Doctor" asp-route-id="@obj.user_id"><i class="fas fa-ellipsis-h"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            }
       }
    </div>
    <div id="noResults" style="display: none;" class="text-go col-12 text-center">
        <img src="~/assets/404.svg" alt="Logo" class="img-fluid svg" width="350" />
        <h5>No doctors found. Please refine your search.</h5>
    </div>
</div>

Medlink/Views/User/Login.cshtml
@model UserModel
@{
    ViewData["Title"] = "Login";
}

<style>
    .card {
        background-color: rgb(255, 255, 255,.2);
        border: none;
    }
</style>

<div class="row">
    <div class="col-12 col-lg-6">
        <h1 class="fw-bolder display-2 d-block d-lg-none">Log into your account</h1>
        <h1 class="fw-bolder d-none d-lg-block">Log into your account</h1>
        <div class="p-3 text-center text-lg-start d-none d-lg-block">
            <img src="~/assets/signup.svg" alt="Logo" class="img-fluid mr-2 svg" width="65%" />
        </div>
    </div>
    <div class="col-12 col-lg-6">
        <div class="card">
            <form class="form m-3" method="post">
                @*<div asp-validation-summary="All"></div>*@
                <div class="form-group">
                    <label for="email" class="fw-bolder">Email...</label>
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text text-go"><i class="fas fa-envelope"></i></span>
                        </div>
                        <input id="email" name="email" class="form-control input-group-append" type="email" placeholder="An email address linked with your account" required/>
                        @*<span asp-validation-for="email" class="text-danger"></span>*@
                    </div>
                </div>

                <div class="form-group">
                    <label for="password" class="fw-bolder">Password...</label>
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text text-go"><i class="fas fa-lock"></i></span>
                        </div>
                        <input id="password" name="password"  class="form-control input-group-append" type="password" placeholder="Your account password" required/>
                        @*<span asp-validation-for="password" class="text-danger"></span>*@
                    </div>
                </div>

                <div class="form-group mt-2 text-center">
                    <button class="btn btn-go text-light col-8 btn-lg" type="submit">Login</button>
                    <label>Dont have an account? <a asp-action="Register">Create an account</a> instead</label>
                </div>
            </form>

        </div>
    </div>
</div>